# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "https://qmonnet.github.io"
baseurl: "/whirl-offload"
permalink: /:year/:month/:day/:title/

# Site meta
title: Whirl Offload
description: Superfast networking technologies and open-source software — among other things.<br /> A blog about my work at <a href='http://www.6wind.com/'>6WIND</a>.

author: Quentin Monnet • 6WIND

repository: "qmonnet/whirl-offload"

socnet_users:
  - twitter_username: Qeole
    github_username:  qmonnet
  - twitter_username: 6WINDsoftware
    github_username:  6WIND

# Build settings
markdown: kramdown
